"""add_fk_indexes

Revision ID: 5578678f6001
Revises: b1b12eb08eaa
Create Date: 2026-06-30 07:59:26.222104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5578678f6001'
down_revision: Union[str, Sequence[str], None] = 'b1b12eb08eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blockers_update_id'), 'blockers', ['update_id'], unique=False)
    op.alter_column('daily_updates', 'planned_work',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_daily_updates_user_id'), 'daily_updates', ['user_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_employee_id'), 'risk_scores', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_scores_employee_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_daily_updates_user_id'), table_name='daily_updates')
    op.alter_column('daily_updates', 'planned_work',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_blockers_update_id'), table_name='blockers')
    # ### end Alembic commands ###
